language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.8
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-5

before_script: |
  export CC=${TRAVIS_CC}${TRAVIS_TOOLCHAIN_VERSION}
  export CXX=${TRAVIS_CXX}${TRAVIS_TOOLCHAIN_VERSION}
  mkdir build && cd build && cmake ..
script: make VERBOSE=1 && make VERBOSE=1 test


