language: cpp
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.8
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-4.8
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=gcc
        - TRAVIS_CXX=g++
        - TRAVIS_TOOLCHAIN_VERSION=-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
            - george-edison55-precise-backports
          packages:
            - clang-3.5
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=clang
        - TRAVIS_CXX=clang++
        - TRAVIS_TOOLCHAIN_VERSION=-3.5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - george-edison55-precise-backports
          packages:
            - clang-3.6
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=clang
        - TRAVIS_CXX=clang++
        - TRAVIS_TOOLCHAIN_VERSION=-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - george-edison55-precise-backports
          packages:
            - clang-3.7
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=clang
        - TRAVIS_CXX=clang++
        - TRAVIS_TOOLCHAIN_VERSION=-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake
            - cmake-data
            - doxygen
      env:
        - TRAVIS_CC=clang
        - TRAVIS_CXX=clang++
        - TRAVIS_TOOLCHAIN_VERSION=-3.8

before_script: |
  export CC=${TRAVIS_CC}${TRAVIS_TOOLCHAIN_VERSION}
  export CXX=${TRAVIS_CXX}${TRAVIS_TOOLCHAIN_VERSION}
  mkdir build && cd build && cmake ..
script: make VERBOSE=1 && make VERBOSE=1 test


